INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (1, 1, 'restaurant', 'Ресторан');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (2, 1, 'fastfood', 'Фастфуд');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (3, 1, 'coffee_bakery', 'Кафе/Выпечка');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (4, 1, 'local_cuisine', 'Местная кухня');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (5, 1, 'business_lunch', 'Бизнес ланч');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (6, 1, 'sportbar', 'Спортбар');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (7, 1, 'terrace', 'Терраса');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (8, 1, 'kid_playground', 'Детская площадка');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (9, 1, 'kidmenu', 'Детское меню');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (10, 1, 'romantique', 'Романтика');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (11, 1, 'panoramic_cityvi', 'Панорама');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (12, 2, 'for_kid', 'для детей');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (13, 2, 'interactive', 'Интерактивный');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (14, 2, 'art', 'Исскуство');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (15, 2, 'history', 'Исторический');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (16, 2, 'speciality', 'Особый');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (17, 2, 'audioguide', 'Аудиогид');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (18, 3, 'souvenir_shop', 'Сувениры');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (19, 3, 'delikatessen', 'Деликатесы');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (20, 4, 'drama_theatre', 'Драматический');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (21, 4, 'opera_and_ballet', 'Опера/Балет');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (22, 4, 'showtheatre', 'Шоу');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (23, 4, 'nightlife', 'Ночное');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (24, 5, 'architecture', 'Архитектура');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (25, 5, 'churche', 'Религиозный');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (26, 5, 'citygarden', 'Парк');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (27, 5, 'artspace', 'Арт-пространство');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (28, 5, 'bridge', 'Мост');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (29, 5, 'monument', 'Памятник');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (30, 5, 'fountain', 'Фонтан');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (31, 5, 'panoramic_cityvi', 'Панорама');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (32, 2, 'architecture', 'Архитектура');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (33, 2, 'churche', 'Религиозный');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (34, 4, 'architecture', 'Архитектура');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (35, 1, 'souvenir_shop', 'Сувениры');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (36, 1, 'delikatessen', 'Деликатесы');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (37, 5, 'souvenir_shop', 'Сувениры');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (38, 5, 'art', 'Исскуство');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (39, 5, 'history', 'Исторический');
INSERT INTO motu_test.filter (id, category_id, name, title) VALUES (40, 5, 'speciality', 'Особый');