INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (3, 2, 'Эрмитаж. Зимний дворец', 'Hermitage. Winter Palace', 'Зимний дворец - бывший императорский дворец, в настоящее время входит в состав главного музейного комплекса Эрмитаж', 'гос.федеральное учреждение', '3295', '191055, Санкт-Петербург, пл. Дворцовая, 2', '59.939741', '30.314803', 'форма на сайте', '+7 (812) 710-96-25', 'hermitagemuseum.org', '2020-11-19 17:57:58', null, null, 'Центральный', 20, 0, 240, 700, '9-00', '20-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (5, 2, 'Исаакиевский собор', 'St. Isaac''s Cathedral', 'Музей-памятник "Исаакиевский собор" - один из наиболее значительных художественных музеев России, пользующийся известностью во многих зарубежных странах.
  Исаакиевский собор - уникальный памятник отечественной архитектуры и один из лучших кафедральных соборов Европы. Это выдающийся образец русского культового искусства.', 'гос.федеральное учреждение', '3298', '190031, Санкт-Петербург, Исаакиевская площадь, 4', '59.934039', '30.306129', 'office@cathedral.ru', '+7 (812) 315-97-32', 'cathedral.ru', '2020-11-19 17:57:58', null, 'St. Isaac’s Cathedral is an outstanding monument of Russian architecture of the 19th century and one of the greatest dome constructions in the world, smaller in size only in comparison with the Cathedral of St. Peter in Rome, St. Paul’s Cathedral in London and Santa Maria del Fiore Cathedral in Florence', 'Адмиралтейский', 20, 0, 60, 600, '9-00', '20-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (7, 2, 'Михайловский замок', 'Mikhailovsky Castle (Russian Museum)', 'Ансамбль Михайловского замка с двумя павильонами Кордегардий. 1797-1801 гг., архитекторы В. Бренна и В. Баженов. Единственное в России дворцовое сооружение в стиле романтического классицизма. Строился как парадная резиденция императора Павла I. Название получил в честь Архангела Михаила - небесного покровителя Дома Романовых. После убийства, произошедшего здесь в ночь с 11 на 12 марта 1801 года, замок потерял значение парадной резиденции, перешел в ведение Министерства Императорского двора и постепенно пришел в запустение. С 1823 года здесь разместилось Николаевское Инженерное училище, давшее замку новое название - Инженерный.', 'гос.федеральное учреждение', '3304', '191023, Санкт-Петербург, Садовая улица, 2', '59.93989', '30.337753', 'info@rusmuseum.ru', '+7 (812) 595-42-48', 'rusmuseum.ru', '2020-11-19 17:57:58', null, 'Among the galaxy of magnificent palaces and mansions of old St. Peterburg the Mikhailovskiy castle occupies a special place whilst still Grand Duke, Paul I was already considering building his own residence, and more then 10- years different architects like Vasiliy Bazhenov were involved in the project. But Emperor lived in it for only 40 days, he was murdered in his bedroom. After this bloody event in the castle was open the main Engeneering School.', 'Центральный', 10, 0, 120, 400, '9-00', '20-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (11, 2, 'Петропавловская крепость', 'St. Peter and Paul Fortress', 'Петропавловская крепость, основанная Петром I в 1703 году, - уникальный памятник истории, архитектуры и фортификационного искусства XVIII-XX веков. Доминанта архитектурного ансамбля - Петропавловский собор (1712-1733, арх. Д. Трезини).', 'гос.федеральное учреждение', '3312', '197046, Санкт-Петербург, Петропавловская крепость', '59.950111', '30.315128', 'spbmuseuminfo@yandex.ru', '+7 (812) 330-64-31', 'spbmuseum.ru', '2020-11-19 17:57:58', null, 'Founded by Peter the Great in 1703, St. Peter and Paul Fortress is considered a unique historical, architectural and fortification art monument of XVIII-XIX centuries. Its architectural ensemble is focused around St. Peter and Paul Cathedral built in 1712-1733 by architect Domenico Tresini.', 'Петроградский', 20, 0, 180, 500, '9-00', '20-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (15, 2, 'Церковь воскресения Христова (Спас на Крови)', 'Church of the Resurrection (Church of the Savior o', 'Государственный исторический собор с уникальной декоративной мозаикой. Собор сооружён в память того, что на этом месте 1 марта 1881 года в результате покушения был смертельно ранен император Александр II.', 'государственное федеральное учре', '3319', '191011, Санкт-Петербург, наб. канала Грибоедова, 2, литера А', '59.939971', '30.329083', 'dirspas@cathedral.ru', '+7(812)3151636;', 'cathedral.ru', '2020-11-19 17:57:58', null, 'State historical monument with unique mosaic decorations. This Church was built on the place where Tsar Alexander II was assassinated and was dedicated in his memory.', 'Центральный', 20, 0, 30, 500, '9-00', '20-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (21, 2, 'Всероссийский музей А.С. Пушкина. Мемориальный Муз', 'National Pushkin Museum', 'Мемориальная квартира - последнее место проживания поэта А.С.Пушкина', 'федеральные (Министерство Культу', '4126', '191186, Санкт-Петербург, наб. р. Мойки, 12', '59.941083', '30.321312', 'vmp@museumpushkin.ru', '+7 (812) 571-35-31', 'museumpushkin.ru', '2020-11-19 17:57:58', null, 'Memorial apartment is the last lodgings of Russian poet Alexander Pushkin', 'Центральный', 10, 0, 60, 800, '9-00', '20-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (30, 2, 'Государственный литературный музей " XX век"', 'State Literary Museum " The XXth Century"', 'Мемориальная квартира М.М.Зощенко и музей советской литературы ХХ века', 'Городские (комитет по культуре)', '4135', '191186, Санкт-Петербург, ул. Малая Конюшенная, 4/2, кв. 119', '59.936566', '30.325372', 'info@museum-xxvek.ru', '+7 (812) 571-78-19', 'museum-xxvek.ru', '2020-11-19 17:57:59', null, 'Memorial apartment of Mikhail Zoshchenko, the exposition dedicated to Soviet literature of XX century', 'Центральный', 10, 0, 60, 500, '9-00', '20-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (42, 2, 'Государственный музей истории Санкт-Петербурга. Му', 'State Museum of The History of Saint-Petersburg. P', 'Экспозиции, посвященные истории печатного дела в Санкт-Петербурге и доходных домов', 'филиал', '4147', '191186, Санкт-Петербург, наб. р. Мойки, 32', '59.938257', '30.320144', 'gmi@spbmuseum.ru', '+7 (812) 571-02-70', 'spbmuseum.ru', '2020-11-19 17:57:59', null, 'Expositions dedicated to the history of St. Petersburg printing and tenement buildings', 'Центральный', 10, 0, 40, 300, '9-00', '20-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (229, 2, 'Титикака', 'TITIQAQA', 'В музее рекордов и фактов «Титикака» собраны экспонаты, которые развлекают и удивляют гостей. Можно увидеть более 70 необычных экспонатов, которые были выкуплены у коллекционеров, на аукционах и привезены из дальних путешествий. Гостей ожидает несколько тематических залов.', 'негосударственное учреждение', '18464', '191186, Санкт-Петербург, ул. Казанская, д. 7 (Пространство Казанская 7)', '59.932002', '30.320831', 'info@titiqaqa.ru', '+7 (812) 982-29-36', 'https://titiqaqa.ru', '2020-11-19 17:58:03', null, null, 'Центральный', 10, 20, 60, 800, '9-00', '20-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (235, 4, 'Александринский театр (Российский государственный', 'Alexandrinsky Theatre', null, 'гос. федеральное учреждение', '4316', '191023, Санкт-Петербург, Островского пл., д.6', '59.930705', '30.337886', 'theatre@alexandrinsky.ru', '+7(812) 312 15 45', 'www.alexandrinsky.ru', '2020-11-19 18:03:50', null, null, null, 20, 0, 180, 1000, '20-00', '23-30');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (237, 4, 'Большой драматический театр им. Г.А. Товстоногова', 'Tovstonogov Bolshoy Drama Theatre', null, 'гос. федеральное учреждение', '4318', '191023, Санкт-Петербург, набережная реки Фонтанки, д.65', '59.927351', '30.330924', 'bdt@bdt.spb.ru', '+7 812 244-10-71; 244-10-75', 'www.bdt.spb.ru', '2020-11-19 18:03:50', null, null, null, 20, 0, 180, 1500, '20-00', '23-30');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (255, 4, 'Санкт-Петербургский Большой театр кукол', 'Saint-Petersburg Big Theatre of Puppets', null, 'гос. городское учреждение', '4338', '191014, Санкт-Петербург, ул. Некрасова, д.10', '59.939059', '30.352052', 'btkpuppets@gmail.com', '+7(812)273-66-72; +7(812)272-82-15', 'www.puppets.ru', '2020-11-19 18:03:50', null, null, null, 20, 0, 90, 500, '10-00', '22-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (257, 4, 'Санкт-Петербургский государственный академический', 'Mikhailovsky Opera and Ballet Theatre', null, 'гос. городское учреждение', '4340', '191011, Санкт-Петербург, Пл. Искусств, д.1', '59.937756', '30.329567', 'office@mikhailovsky.ru', '+7(812)5954305; +7(812)5954319', 'www.mikhailovsky.ru', '2020-11-19 18:03:50', null, null, null, 20, 0, 180, 8000, '20-00', '23-30');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (291, 4, 'Эрмитажный театр', 'Hermitage Theatre', 'Уютный театр, находится в здании резиденции российских царей, исторические интерьеры', 'Государственное федеральное учре', '4379', '191186, Санкт-Петербург, дворцовая наб., д.34', '59.941682', '30.317719', 'theatre@hermitage.ru', '+7(812)7109030;', 'http://www.hermitagemuseum.org/wps/portal/hermitage/what-s-on/articles/music_theatre/?lng=ru, https://vk.com/hermitagetheatre', '2020-11-19 18:03:51', null, null, null, 10, 10, 180, 4000, '20-00', '23-30');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (295, 4, 'Мариинский театр', 'Mariinsky Theatre', 'Самый знаменитый театр оперы и балета Санкт-Петербурга', 'федеральное государственное бюдж', '16001', '190121, Санкт-Петербург, ул. Декабристов, д.34', '59.92571', '30.294282', 'post@mariinsky.ru', '+7 812 326 41 41', 'https://www.mariinsky.ru/', '2020-11-19 18:03:51', null, null, null, 20, 0, 210, 6000, '20-00', '23-30');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (304, 4, 'Музыкальный Театр Детей Марины Ланда "Радуга" (АНО', 'Children''s Musical Theatre of Marina Kfylf "Rainbo', null, 'негосударственное учреждение', '18946', '191014, Санкт-Петербург, ул. Маяковского, д. 19/15', '59.938568', '30.355527', 'iinfo@teatrlanda.ru', '+7 921-424-64-65', 'http://teatrlanda.ru', '2020-11-19 18:03:51', null, null, null, 10, 10, 90, 1000, '10-00', '21-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (337, 4, 'Фольклорно-этнографическая студия "Пан-Театр" (АНО', 'Folklore and Ethnographic Studio "Pan-Theatre"', null, 'негосударственное учреждение', '19026', '1911186, Санкт-Петербург, Инженерная ул., 4/1, пом. 18 (Российский Этнографический музей)', '59.937785', '30.334712', 'panteatre@gmail.ru', '8 (812) 998-44-95', '-', '2020-11-19 18:03:54', null, null, null, 10, 10, 90, 1000, '18-00', '22-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (357, 2, 'Лофт Проект Этажи', 'Loft Project ETAGI', 'Культурный центр ЛОФТ ПРОЕКТ ЭТАЖИ — пионер лофт-дизайна и одно из крупнейших выставочных пространств в Санкт-Петербурге. С 2007 года центр занимает площадь бывшего хлебозавода на Лиговском пр., 74. На сегодняшний день на территории в 3000 квадратных метров находятся более 150 креативных проектов — магазинчики, выставки, кафе и галереи! На третьем этаже вас ждёт Кофейня Зелёная Комната с большой открытой терассой, а над 5 этажем — пространство КРЫША! 

Крыша ЛОФТ ПРОЕКТ ЭТАЖИ — большая, оборудованная, безопасная обзорная площадка площадью более 1200 кв. м. Отсюда видны многие достопримечательности и открывается отличный вид на Лиговский проспект.', 'негос.учреждение', '13924', 'Санкт-Петербург, пр. Лиговский, д. 74', '59.922034', '30.355502', 'ALL-ONE-MAIL@LOFTPROJECTETAGI.RU', '+7 (812) 458-50-05', 'http://www.loftprojectetagi.ru', '2020-11-19 18:06:10', null, 'Loft Project ETAGI is not only a cultural center, but a pioneer in loft design and one of the largest exhibition spaces in Saint Petersburg. Since 2007, the center occupies the building of a former bakery at Ligovsky, 74. The center currently consists of two modern art galleries, several exhibition areas, the Green Room café, LOCATION Hostel with 3 Design rooms and a rooftop area with a stunning view of the city, all occupying an area of 3000 square meters.', null, 10, 0, 150, 3000, '12-00', '01-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (378, 1, 'Пышечная', 'Pyshechnaya', 'Традиционная местная еда.  Пробовать обязательно', 'ресторан', '6153', 'м. Невский проспект, ул. Большая Конюшенная, 25.', '59.93726', '30.322165', null, '+7 (812) 314-08-68', 'https://vk.com/club74224', '2020-11-19 18:07:10', null, null, null, 5, 5, 30, 500, '10-00', '21-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (392, 1, 'SПБ - Самый Правильный Бар', 'SPB - Bar', null, 'ресторан', '6483', 'м. Гостиный Двор, 191123, Санкт-Петербург, Садовая ул., 14/52', '59.934682', '30.335685', 'office@barspb.ru', '+7 (812) 655-67-10', 'www.barspb.ru', '2020-11-19 18:07:10', null, null, null, 10, 10, 120, 1000, '15-00', '02-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (400, 1, 'КОНТАКТ БАР', 'CONTACT BAR', null, 'ресторан', '6501', 'м. Владимирская, 191002, Санкт-Петербург, Владимирский пр., 17', '59.928812', '30.345908', null, '+7  (812) 951-83-95', 'kontaktbar.ru', '2020-11-19 18:07:10', null, null, null, 10, 10, 60, 750, '15-00', '24-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (406, 1, 'Подстреленная гусыня', 'Podstrelennaya gusynya', null, 'ресторан', '6515', 'м. Пл. Восстания, 191036, Санкт-Петербург, ул. Восстания, 17', '59.934934', '30.360946', 'gsmobi@gmail.com', '+7 (812) 719-71-19', 'www.pivnicespb.ru', '2020-11-19 18:07:10', null, null, null, 10, 20, 120, 2500, '12-00', '23-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (452, 1, 'Рибай (Гинза Проджект)', 'Rib eye (Gindza Project)', 'Стейки, фьюжн', 'ресторан', '13904', 'ул. Казанская, д. 7, 2 этаж', '59.932378', '30.321042', null, '+7 (812) 941-73-53', 'vk.com/mv_k7', '2020-11-19 18:07:13', null, null, null, 20, 25, 150, 5000, '12-00', '23-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (485, 1, 'Укроп', 'Ukrop', 'Вегетарианская еда', 'ресторан', '14742', 'Санкт-Петербург, ул. Марата, 23', '59.92786', '30.352843', null, '+7(812)946-30-36', 'cafe-ukrop.ru', '2020-11-19 18:07:13', null, null, null, 10, 20, 90, 2000, '12-00', '23-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (696, 1, 'Lounge Room на Пяти углах', 'Lounge Room', 'LoungeRoom – это сеть кальянных заведений, расположенных в самом центре Санкт-Петербурга. Барная история и авторская кухня поразит своим разнообразием и индивидуальностью.', 'ресторан', '19267', '​Загородный проспект, 11', '59.9265744999999', '30.3430454', 'обратная связь через сайт', '+7 (812) 561‒63‒87', 'lounge-room.ru', '2020-11-19 18:07:15', null, null, null, 20, 15, 90, 1200, '12-00', '23-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (844, 1, 'УеБар', 'Yebar', 'Кухня русская
УЕ!БАР - место, где официанты стебутся над клиентами. 
Они ругаются матом, ведут себя, как хотят, тем самым создают 
самую искреннюю атмосферу, возможную в ресторанной среде. 

Здесь подают горячие у!блюда, пиво и коктейли(от слова “cock”, естественно). 
Можно выбрать коктейль “вилкой в глаз”, а можно “в попу раз”. 
Но лучше оба, вдвое больше удовольствия. 

Здесь гостей посылают в жопу, ведь она обозначает вход в туалет. 
Можно присесть на стул с пиками точёными и поболтать с уе!барменом. 
Кстати, если рассмешишь его, получишь шот.', 'ресторан', '19415', '​Восстания, 12', '59.936015', '30.36', 'Обратная связь через сайт.', '+7‒921‒905‒30‒60', 'yebar.ru', '2020-11-19 18:07:16', null, null, null, 10, 15, 0, 1000, '12-00', '23-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (859, 5, 'Александро-Невская лавра', 'Saint Alexander Nevsky Lavra', 'Один из старейших историков Петербурга пишет, что уже весной 1704 года Петр Великий выбрал место для будущего Петербургского монастыря. Оно, как и все пространство нынешнего Петербурга, было покрыто болотами и лесом и требовало для своего устройства большого труда и времени. Между тем, не прекращавшиеся военные действия в борьбе со шведами за обладание устьем Невы не давали возможности приступить в скором времени к осуществлению мысли об основании в Петербурге монашеской обители. 

В 1710 году, 13 июня, был взят Выборг и, таким образом, была достигнута безопасность столицы со стороны ближайших границ. После этого Государь, будучи в Петербурге, в июле 1710 года "осматривал место, где быть строениям". Тогда и указано было "непременно на том месте быть Монастырю". Определено было именовать монастырь "Живоначальныя Троицы и Святого благоверного Великого князя Александра Невского" и быть по правую сторону Черной речки (первоначально Монастырка, так же как и река Волковка, была частью Чёрной речки. Упоминание об этой реке имеется еще в летописях 1500 г. Когда в 1829 году был построен восточный участок Обводного канала, он разделил реку на две части. Северная часть стала называться Монастыркой по Александро-Невскому монастырю, причём направление течения реки изменилось на обратное: она стала вытекать из Невы и впадать в Обводный канал) каменному монастырскому строению, а по левую - деревянному партикулярному. Назначенный в "тот Монастырь" архимандрит Феодосий водрузил на избранном месте 2 креста: один на правой стороне Черной речки, а другой на левой. На кресте, водруженном на правой стороне, сделана была надпись: "Во имя Отца и Сына и Святаго Духа, повелением Царскаго Пресветлаго Величества на сем месте имеет создатися Монастырь". А на левой стороне Черной речки водружен был крест с надписью: "Что сей крест образует, обонполный то сказует". 

Место, выбранное для Александро-Невского монастыря, имело историческое значение.', 'Религиозные объекты', '5841', 'Санкт-Петербург, Набережная реки Монастырки, 1', '59.921011', '30.388919', 'kanzlei@lavra.spb.ru Канцелярия; pal-centr@lavra.s', '+7(812)2741702 Канцелярия; +7(812)2741612 Паломнич', 'www.lavra.spb.ru', '2020-11-19 18:08:23', null, 'One of the oldest historians of Petersburg writes that in the spring of 1704 Peter the Great chose a place for future Petersburg monastery.  It, as well as all space of present Petersburg, was covered with bogs and the wood and demanded for the device of big work and time.  Meanwhile, not stopping military operations in fight against Swedes for possession the mouth of Neva didn''t give the chance to start shortly implementation of thought of the basis in Petersburg a monastic monastery. 

In 1710, on June 13, Vyborg was taken and safety of the capital was thus reached from the next borders. After that the Sovereign, being in Petersburg, in July, 1710 "I examined a place where to be to structures". Then it was specified "by all means on that place to be to the Monastery". Was determined to call the monastery "Zhivonachalnyya Trinity and Saint Blessed Grand Duke Alexander Nevsky" and to be on the right side of the Black small river (originally Monastyrka as well as the river Volkovka, was part of the Black small river. The mention of this river is available in chronicles of 1500. When in 1829 east site of the Bypass channel was constructed, it divided the river into two parts. The northern part began to be called as Monastyrka across the Aleksandro-Nevsky to a monastery, and the direction of a watercourse changed on the return: it began to follow from Neva and to fall into the Bypass canal) to a stone monastic structure, and on the left - wooden civil. Appointed in "that Monastery" the archimandrite Feodosiy set up 2 crosses on the chosen place:  one on the right side of the Black small river, and another on the left.

The place chosen for the Aleksandro-Nevsky of a monastery, had historical value.', null, 20, 0, 120, 1, '10-00', '18-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (891, 5, 'Собор Казанской Иконы Божией Матери', 'Cathedral of Our Lady of Kazan', 'Массонский храм, построен Строгановым', 'Религиозные объекты', '5873', 'Санкт-Петербург, Казанская площадь, д. 2', '59.934195', '30.324797', 'sobor.go@mail.ru', '+7(812)3144663; +7(812)3145856', 'kazansky-spb.ru', '2020-11-19 18:08:23', null, null, null, 20, 0, 40, 1, '10-00', '18-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (1024, 5, 'Летний сад', 'Summer garden', 'Заложенный в 1704 г. по указу Петра I, Летний сад представлял собой прекрасный образец регулярного парка, самый настоящий дворец под открытым небом, с трельяжными решетками и шпалерами из зелени, «зелеными кабинетами», аллеями, цветочными партерами, фонтанами и скульптурой. После разрушительных наводнений 1777 и 1824 годов Летний сад практически утратил все убранство XVIII века и принял вид пейзажного парка. В нем появились новые сооружения: «Кофейный» и «Чайный» домики, а в 1855 г. в саду был установлен памятник И. А. Крылову.

В мае 2012 г. сад был открыт после реконструкции. Теперь здесь воссозданы разрушенные наводнением еще в конце XVIII в. фонтаны (один из них, подлинный фонтан первой половины XVIII столетия, «Лакоста», можно увидеть в специальном павильоне), воспроизведены прежняя планировка, прежнее зеленое убранство, реставрирована красивейшая ограда, созданная по проекту Ю.Фельтена и П.Егорова. Сейчас оригинальная скульптура Летнего сада заменена на точные копии, поскольку мрамор оказался слишком хрупким и нежным материалом для сурового северного климата. Оригиналы скульптур размещены сейчас в Михайловском замке.

На берегу Фонтанки, недалеко от Невской ограды, находится Летний дворец Петра I. Это единственное сооружение в Летнем саду, сохранившееся с XVIII века. Дворец был построен в 1710-1712 гг. по проекту Доменико Трезини. С трех сторон его омывала вода: Нева – с севера (Нева тогда подступала ко дворцу вплотную), Фонтанка – с востока, с юга – Гаванец, и дворец лишь западным фасадом был обращен в сторону парка. Гаванец был восстановлен реставраторами Русского музея. Это искусственная гавань, которая существовала перед дворцом с момента его постройки в 1710 г. Он использовался для подхода к Летнему дворцу на небольших судах и был засыпан при строительстве гранитной набережной Фонтанки в 80-х годах XVIII в. Летний дворец помнит все наводнения Санкт-Петербурга, и помнит самое страшное из них, случившееся 7 ноября 1824 г., когда вода в Неве поднялась на 421 м. Отметка уровня воды увековечена здесь памятной табличкой.', 'Сады и парки', '13795', 'СПб, Набережная Кутузова, д. 2', '59.949177', '30.345027', null, '+7 (812) 595-42-48', null, '2020-11-19 18:08:27', null, null, null, 20, 0, 120, 1, '10-00', '18-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (1035, 5, 'Марсово поле', 'Field of Mars', 'Марсово поле  — крупнейший мемориально-парковый комплекс в центре Санкт-Петербурга, занимающий площадь почти в девять гектаров. Величественная панорама обширного партерного сквера с памятником жертвам революции ограничена с южной и восточной сторон Летним и Михайловским садами, а северная сторона выходит к Неве и площади Суворова. История Марсова поля восходит к первым годам основания Петербурга.
В 40-х годах XVIII века Потешное поле ненадолго превратилось в место для прогулок – Променад, здесь проложили дорожки, газоны, высадили цветы. Следующее название – Царицын луг Марсово поле получило после постройки Летнего дворца для императрицы Елизаветы Петровны (арх. Ф.-Б. Растрелли), а в конце XVIII века Царицын луг стал военным плацем, где воздвигли монументы, посвящённые победам русской армии и устраивали парады и воинские учения.
В центре поля в 1799 году был установлен Румянцевский обелиск, который теперь находится в сквере у Академии художеств, а в 1801 в южной части поля поставили памятник А. В. Суворову (скульптор М. И. Козловский). Великий полководец изображён в образе бога войны Марса, и с тех пор Марсово поле и приобрело своё настоящее название. Памятник Суворову был в 1818 году перемещён на Суворовскую площадь, с которой открывается великолепный вид на Марсово поле.
Среди наиболее ранних построек ансамбля Марсова поля – Мраморный дворец (1768-1785, арх. А. Ринальди), который сейчас находится в ведении Русского музея. Во дворе Мраморного дворца находится памятник предпоследнему русскому царю Александру III.
Смысловым центром Марсова поля является памятник павшим борцам революции 1917 года, торжественно открытый 7 ноября 1919 года. Гранитные стены памятника с надписями-эпитафиями ограждают братские могилы жертв революции и гражданской войны. В советское время идеология подчёркивала принадлежность павших к большевистскому режиму, но в наши дни памятник приобрёл иное значение – монумента всем погибшим в нелёгкие послереволюционные годы. В 1957 году в центре памятника был зажжён Вечный огонь.
Марсово поле – это символ памяти павших, свидетель торжественных событий в истории русской армии и просто один из красивейших скверов Санкт-Петербурга.', 'Сады и парки', '13809', 'СПб, наб. Лебяжьей канавки / наб. Мойки', '59.931634', '30.307837', null, null, null, '2020-11-19 18:08:27', null, null, null, 10, 0, 30, 1, '0-00', '0-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (1110, 5, 'Сторожевые львы на Адмиралтейской наб.', 'Sentry lions on Admiralteyskaya Embankment', 'В 1832 году Дворцовую пристань украсили фигурами львов и вазами. Вычеканенные из тонкой листовой меди царственно-величавые статуи грозных зверей хорошо видны отовсюду, а их профили чётко прорисовываются на фоне тёмно-серой глади Невы и бледной голубизны неба. 

Скульптуры львов были отлиты в 1832 году на Александровском чугунолитейном заводе в Петербурге. В качестве моделей для литья использовали гипсовые слепки с флорентийских львов, которые находятся в Академии Художеств.', 'Памятники', '3281', 'г. Санкт-Петербург, Адмиралтейская наб./Admiralteiskaya nab.', '59.938153', '30.30534', null, null, null, '2020-11-19 18:08:28', null, 'On the embankment in front of the east wing of the Admiralty, Palace Pier is a broad flight of granite steps leading down to the Neva. The two lions that flank the steps on pedestals are among the best known sculptures in St. Petersburg. The pier, designed by Carlo Rossi, was originally situated right next to the Winter Palace, but moved 1914-1916 to make way for the construction of Palace Bridge.
The lions, modeled on marble statues on the Piazza della Signoria inFlorence, were constructed from bronze leaf by the German craftsman, Johan Gottlieb Prang to designs by sculptor Ivan Prokofiev, and unveiled in 1832. Among many examples of ceremonial lions in St. Petersburg, they are undoubtedly the most famous.', null, 10, 0, 20, 1, '0-00', '0-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (1111, 5, 'Александровская колонна', 'Alexander Column', 'Сооружена: 1830-34 
Архитектор: А. А. Монферран  
Высота монолита - более 25,5 м, нижний диаметр 3,66 м, верхний - 3,19 м, масса около 600 т. 
Общая высота колонны - 47,5 м. 

Памяник победы в Отечественной войне 1812 г. на Дворцовой площади. Названа в честь императора Александра I. Венчает колонну бронзовая фигура ангела (его лицу приданы черты императора Александра I), попирающего крестом змею - символ победы добра над злом (скульптор Б. И. Орловский). Постамент украшен бронзовыми барельефами аллегорического содержания (скульптор П. В. Свинцов, И. Леппе, по эскизам Дж. Б. Скотти).  Александровская колонна - композиционный центр, важнейший элемент архитектурного ансамбля Дворцовой площади.', 'Памятники', '3282', 'г. Санкт-Петербург, Дворцовая площадь', '59.938977', '30.315962', null, null, null, '2020-11-19 18:08:28', null, 'Built: 1830-34 
Architect: A.A. Montferrand
The height of the monolithis - over 25,5 m, the lower diameter - 3,66 m, diameter at the top - 3,19 m, weight - about 600 t.
The general height of the Column is 47,5 m.

Alexander Column is a monument to a victory in the Patriotic War of 1812 on the Palace Square. It was named in honor of the emperor Alexander I. Adorning the column, there is a bronze figure of an angel (its face resembling that of the emperor Alexander I) trampling  on a snake with a cross, a symbol of the triumph of good over evil (sculptor B.I. Orlovsky). The pedestal is decorated with allegorical bronze bas-reliefs (sculptor P.V. Svintsov, I. Leppe, the sketches made by J.B. Scotty). Alexander Column is the compositional center and the most important element of an architectural complex of the Palace Square.', null, 20, 0, 20, 1, '0-00', '0-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (1113, 5, 'Здание Главного Адмиралтейства', 'The Building of the Main Admiralty', 'Здание Адмиралтейства которое мы видим сегодня, было построено между 1806 и 1823 году по проекту архитектора Адриана Захарова. Он сохранил оригинальную планировку здания, но превратил его в прекрасный пример русского ампира, с рядами белых колонн, рельефами и многочисленными статуями. Позолоченный шпиль Адмиралтейства (и особенно его флюгер Кораблик - "маленький корабль") является одним из символов Санкт-Петербурга. Башня Адмиралтейства, увенчаная золотым шпилем, является центром сразу трех главных улиц города; Невский проспект, Гороховая улица и Вознесенский проспект. Здание Адмиралтейства можно увидеть по всей длине каждой из них.', 'Памятники', '3291', 'г. Санкт-Петербург, Адмиралтейский проезд, 1', '59.937356', '30.308651', null, null, null, '2020-11-19 18:08:28', null, 'The Admiralty building we see today was built between 1806 and 1823 by the architect Adrian Zakharov. He maintained the original plan of the building, but turned it into a marvelous example of the Russian Empire style, with rows of white columns, wonderful relief detail and numerous statues. The gilded spire of the Admiralty (and particularly its weather-vane - "the little ship") is one of St. Petersburg’s famous landmarks. The Admiralty tower, topped with its golden spire, is the focal point of three of the city’s main streets; Nevsky Prospekt, Gorokhovaya Street and Voznesensky Prospekt, and can be seen along the entire length of each one.', null, 20, 0, 20, 1, '0-00', '0-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (1177, 5, 'Екатерине II', 'To Catherine II', 'Дата открытия: 24 ноября 1873 г.
Автор проекта: М. О. Микешин 
Скульпторы: М. А. Чижов, А. М. Опекушин 
Архитекторы: Д. И. Гримм, В. А. Шретер 
Материалы: бронза – скульптура, текстовая доска; гранит, розовый и серый, полированный – постамент; чугун – ограда.
Общая высота памятника — 14,9 м, высота скульптуры Екатерины II — 4,2 м, высота постамента — 10,7 м.

В 1860 г. Академией художеств был объявлен конкурс на сооружение памятника Екатерине II для Царского Села. Одобрение получил проект художника М. О. Микешина. Через год по этому проекту была выполнена модель памятника и отлита из бронзы на заводе Шопена. Модель, отправленная на Всемирную выставку в Лондон, удостоилась медали.
В 1862 г. М.О. Микешин получил непосредственно от Александра II заказ на создание памятника по этой модели. В следующем году петербургский генерал-губернатор князь А. А. Суворов обратился к императору с предложением установить памятник в сквере напротив «Александрийского театра в Санкт-Петербурге, в виду Публичной библиотеки, учреждение которой принадлежит мудрой императрице». Микешин составил новый, более значительный по размерам проект, отличный от модели 1861 г. К середине августа 1864 г. новая модель памятника была завершена, получив Высочайшее утверждение.
С самого начала разработки темы художнику было ясно, что монументальный портрет императрицы должен дополняться изображениями ее современников, прославивших своими заслугами век Екатерины. 30 марта 1867 г. советом Академии художеств принята модель статуи Екатерины, выполненная М. А. Чижовым. К февралю 1874 г. число фигур на постаменте было увеличено до девяти: Г. А. Потемкин, П. А. Румянцев, А. В. Суворов, В. Я. Чичагов, А. Г. Орлов, А. А. Безбородко, И. И. Бецкой, Г. Р. Державин, Е. Р. Дашкова. Скульптуры деятелей екатерининского царствования вылепил А. М. Опекушин. Отливка бронзовой скульптуры произведена на бронзолитейном заводе Кохуна (фирма «Никольс и Плинке»). Проект архитектурного решения монумента разработал архитектор Д. И. Гримм. По его проекту изготовлены также массивные фонари-канделябры и ограда памятника из лавровых гирлянд. Орнаментальные детали фонарей выполнялись по рисункам архитектора В. А. Шретера.
С июня 1869 г. начались работы по сооружению памятника: ломка гранита в Финляндии, устройство фундаментов. Одновременно с сооружением памятника шли работы по созданию сквера.
Торжественное открытие памятника было приурочено ко дню святой Екатерины — именинам императрицы — 24 ноября.
В годы Великой Отечественной войны памятник не был укрыт.', 'Памятники', '8954', 'г. Санкт-Петербург, пл. Островского', '59.932329', '30.336727', null, null, null, '2020-11-19 18:08:28', null, 'The date of unveiling: 24th of November 1873
Author of the monument: M. O. Mikeshin
Sculptor: M. A. Chizhov, A. M. Opekushin
Architects: D. I. Grimm, V. A. Shreter
Materials: bronze - the sculpture, text board; polished pink and grey granite - the pedestal; cast iron  - the fence.
The height of the monument is 14,9 m, the height of the Catherine II sculpture is 4,2 m, the height of the pedestal is 10,7 m.

The monument was erected on Alexandrinskaya Square (since 1923, called Ostrovskogo Square) in front of the Alexandrinsky Theatre on 24 November 1873. The artist M.O. Mikeshin started working on the project in 1860. The designs were approved in 1872, at which point the erection of the pedestal, made of 600 Serdobolsk granite blocks, had already began. Special ships were built to carry the stones, which weighed up to 50 tons, from the Valaam Archipelago Island. Special portable rails, made at the San Galli Factory, were built from the ship landing to the construction site. The crowning memorial sculpture of Empress Catherine II was made by the sculptor M.A. Chizhov. Surrounding the pediment are nine sculptural portraits of nobles from Catherine the Great''s time (sculptor A.M. Opekushin); these are organised into groups of generals (P.A. Rumyantsev, G.A. Potemkin, A.V. Suvorov), officials (A.A. Bezborodko, I.I. Betskoy), naval commanders (V.Y. Chichagov, A.G. Orlov) and cultural figures (G.R. Derzhavin, E.R. Dashkova). A plan for an additional ensemble with six sculptures and 23 busts for Catherine''s park was not carried out. The monument is 14.9 metres high. The careful execution and expressiveness of the sculptures are characteristic of this form of realism from the second half of the 19th century. The monument''s large shapes changed the scale of architectural ensembles previously created by K.I. Rossi. During the years of the Great Patriotic War of 1941-45, the monument was not covered or safe-guarded, but luckily was not damaged by artillery fire and bombing. In 1972, restoration work was carried out.', null, 20, 0, 20, 1, '0-00', '0-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (1268, 5, 'Уровням подъема воды во время наводнений', 'Obelisk to the water marks of Saint Petersburg flo', 'Адрес: Мойки реки наб., 89

Архитектор: Петров Василий Александрович (1916-1992)

Открыт в 1971 г.

Материалы: гранит — обелиск; бронза — пояски; металл, ковка — декоративная композиция.

Надписи: на обелиске с трех сторон обозначение шкалы врезными тонированными знаками:
1 м, 1 метр, 1 м;
2 м, 2 метра,2 м;
3 м, 3 метра, 3 м;
4 м, 4 метра, 4 м;
5 м, 5 метров, 5 м и промежуточных делений — штрихами;
на каждом из пяти поясов с трех сторон литыми знаками:
1824 г, Наводнение 1824 г, 1824 г;
1924 г, Наводнение 1924 г, 1924 г;
1955 г, Наводнение 1955 г, 1955 г;
1903 г, Наводнение 1903 г, 1903 г;
1967 г,Наводнение 1967 г, 1967 г

Обелиск установлен в соответствии с решением Ленгорисполкома. Научные данные для разработки проекта — отметки уровней подъема воды — предоставлены Гидрологическим институтом и метеослужбой Северо-Западного региона. По этим сведениям научного обоснования для отметки высоты подъема воды в XVIII в. не существует, и поэтому на обелиске первой дана отметка о наводнении 1824 г. Обелиск увенчан декоративной композицией с трезубцем, на трех сторонах расположены солнечные часы.
Следует отметить, что в городе имеются и другие памятные знаки, связанные с темой наводнений: главный футшток — в г. Кронштадте, ординар водомерного поста — на набережной Невы возле Горного института, многочисленные мемориальные доски с отметками уровня подъема воды. Наиболее известны 6 мемориальных досок и футшток под аркой Невских ворот Петропавловской крепости.

Высота памятника — 10 м.', 'Памятники', '9073', 'г. Санкт-Петербург, наб. Мойки, 89/Nab. reki Moiki, 89', '59.931612', '30.306903', null, null, null, '2020-11-19 18:08:29', null, 'Opened in 1971

Materials: granite - obelisk; bronze - bands; metal, forging - decorative composition.

Obelisk was created in accordance with the decision of the Leningrad Executive Committee. Scientific data of the water marks was provided by the Hydrological Institute and Meteorological Service of Northwest region. According to this information there are no precise figures for the water rise in the XVIII century and therefore the first given mark of the flood is 1824. The obelisk is topped with a decorative composition with a trident. All three sides of the obelisk have sundials.

The height of the monument - 10 m.', null, 10, 0, 20, 1, '0-00', '0-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (1284, 5, 'Чижик-Пыжик', 'Chizhik-Pyzhik', 'Установлен в 1994 г. на реке Фонтанке рядом с 1-м Инженерным мостом, напротив дома № 6, где в 1835 г. по инициативе принца Петра Ольденбургского было основано Императорское училище правоведения. Студенты училища носили мундиры жёлто-зеленого цвета, который напоминал оперение чижа, за что их прозвали "чижиками-пыжиками".

Автор памятника Резо Габриадзе. Эта фигурка является одним из самых маленьких памятников в Санкт-Петербурге. Его высота всего 11 см, а вес - около 5 кг. За время существования памятника его несколько раз похищали, но каждый раз скульптура возвращалась на место.

Существует поверье, согласно которому, если загадать желание и попасть в Чижика-Пыжика монеткой, то желание обязательно сбудется.', 'Памятники', '9096', 'г. Санкт-Петербург, на Фонтанке, у Михайловского (Инженерного) замка рядом с 1-м Инженерным мостом, напротив дома № 12/1.', '59.939095', '30.315868', null, null, null, '2020-11-19 18:08:29', null, 'Chizhik-Pyzhik, a decorative composition on the abutment of First Inzhenerny (Engineers'') Bridge spanning the Fontanka River; shaped as a tiny bronze bird resting on a granite console (architect V. B. Bukhaev). 
The author and creator of the model is Georgian painter and theatre figure R. Gabriadze; whose unveiling of the monument on 12 November 1994 was timed to the Golden Ostap humour festival. 
This character of city folklore ("Chizhik-Pyzhik, where have you been? I drank vodka on the Fontanka River") originates from the Law School located on Fontanka River Embankment. Its students wore black and yellow uniform, so they were nicknamed "chizhiks-pyzhiks" ("chizhik" is Russian for "siskin").', null, 10, 0, 20, 1, '0-00', '0-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (1341, 5, 'Синий мост', 'Siny Bridge', 'Самый широкий мост Санкт-Петербурга', 'Мосты', '3314', 'Санкт-Петербург, Синий мост', '59.931869', '30.309328', null, null, null, '2020-11-19 18:08:30', null, null, null, 10, 0, 20, 1, '0-00', '0-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (1525, 1, 'Банщики', 'Banshiki', 'Русская кухня, рядом настоящая русская баня ', 'ресторан', '!', 'Дегтярная ул., 1А', '59.930313', '30.370198', null, '+7 (921) 941-17-44', null, '2020-11-25 16:59:22', '2020-11-28 06:10:27', null, null, 20, 25, 90, 4000, '12-00', '23-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (1526, 1, 'Музей русской водки', 'Russian vodks museum', 'Русская кухня, бутик', 'ресторан', '!', 'Конногвардейский бульвар, д. 4  Санкт-Петербург 190000, Россия', '59.933023', '30.299174', null, '+7 (921) 943-14-31', 'http://www.vodkamuseum.su/', '2020-11-25 16:59:22', '2020-11-28 06:10:27', null, null, 20, 20, 60, 3700, '12-00', '23-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (1527, 1, 'Ресторан "Мансарда"', 'Mansard', 'Европейская кухня, фьюжн', 'ресторан', '!', 'ул. Почтамтская, 3-5 Бизнес центр, 6й этаж, Санкт-Петербург 190000 Россия', '59.932974', '30.30367', null, '+7 (812) 640-16-16', null, '2020-11-25 16:59:22', '2020-11-28 06:10:27', null, null, 20, 25, 120, 3900, '12-00', '23-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (1528, 3, 'Белуга Делюкс', 'Beluga Delux', 'Магазины сувениров и деликатесов', 'магазин', '!', '​Искусств площадь, 5​, 1 этаж', '59.937099', '30.328988', 'http://belugadeluxe.com/', '+7 (812) 325‒82‒64', null, '2020-11-25 16:59:22', null, null, null, 10, 20, 30, 10000, '9-00', '20-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (1529, 3, 'Норд Вэй', 'Northway', 'Магазин подарков и сувениров ', 'магазин', '!', 'Санкт-Петербург, Труда площадь, 2, 1 этаж', '59.933284', '30.291374', 'http://belugadeluxe.com/', '+7 (812) 312-20-62', null, '2020-11-25 16:59:23', null, null, null, 10, 20, 30, 7000, '9-00', '20-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (1530, 3, 'Красный Октябрь', 'Red October', 'Магазин подарков и сувениров ', 'магазин', '!', 'Санкт-Петербург, Конногвардейский бульвар, 6', '59.931619', '30.293833', null, '+7 (812) 312-02-81', null, '2020-11-25 16:59:23', null, null, null, 10, 20, 30, 3000, '9-00', '19-00');
INSERT INTO motu_test.provider (id, category_id, brand_name, brand_name_en, description, object_type, short_description, address, latitude, longitude, email, phone, web_url, created_at, updated_at, description_en, area, rating, discount, vist_term, average_price, from_operation_hour, to_operation_hour) VALUES (1531, 3, 'Императорский фарфор', 'Imperial Porcelain', 'Магазин посуды, подарков и сувениров ', 'магазин', '!', 'Санкт-Петербург, Невский проспект, 60', '59.934033', '30.338775', 'ipm.ru', '+7 (812) 571-32-62', null, '2020-11-25 16:59:23', null, null, null, 10, 20, 30, 15000, '10-00', '22-00');